from .constants import COLOR_ITEM_ARMOR, COLOR_ITEM_WEAPON
from .mixins import (
    AbilitiesMixin,
    AutoexploreMixin,
    CombatMixin,
    CombatAIMixin,
    ControlsMixin,
    DeathUIMixin,
    FloorGenerationMixin,
    GameCoreMixin,
    HarvestMixin,
    SocialQuestsMixin,
    InputMixin,
    InspectMixin,
    InventoryMixin,
    InventoryUseMixin,
    JournalUIMixin,
    LogUIMixin,
    MenuUIMixin,
    MovementMixin,
    OverlayClickMixin,
    OverlayControllerMixin,
    OverlayEventMixin,
    OverlayInputMixin,
    RareNPCsMixin,
    PopulationMixin,
    QuestTextMixin,
    ResidentBoonsMixin,
    ServiceBoonsMixin,
    ResidentsMixin,
    RespawnMixin,
    ResidentsTownMixin,
    QuestsMixin,
    RewardsUIMixin,
    StatsMixin,
    LandmarkServicesMixin,
    TerrainMixin,
    TownReactionsMixin,
    TownsMixin,
    TradeMixin,
    TownsServicesMixin,
    TownsRevealMixin,
    TuningMixin,
    UIMixin,
    VisibilityMixin,
    WorldGeographyMixin,
    WorldMixin,
    WorldTravelMixin,
    WorldMapPreviewMixin,
    WorldMapSettlementMixin,
    WorldMapStatsMixin,
    WorldMapUIMixin,
    WorldStateMixin,
    XPMixin,
)

class Game(
    GameCoreMixin,
    TuningMixin,
    AbilitiesMixin,
    WorldGeographyMixin,
    WorldMixin,
    WorldTravelMixin,
    XPMixin,
    LandmarkServicesMixin,
    TownReactionsMixin,
    TownsMixin,
    TradeMixin,
    TownsServicesMixin,
    TownsRevealMixin,
    ResidentBoonsMixin,
    ServiceBoonsMixin,
    ResidentsTownMixin,
    WorldStateMixin,
    FloorGenerationMixin,
    TerrainMixin,
    WorldMapPreviewMixin,
    WorldMapSettlementMixin,
    WorldMapStatsMixin,
    WorldMapUIMixin,
    OverlayClickMixin,
    OverlayControllerMixin,
    OverlayEventMixin,
    OverlayInputMixin,
    InputMixin,
    RareNPCsMixin,
    PopulationMixin,
    ResidentsMixin,
    RespawnMixin,
    MovementMixin,
    RewardsUIMixin,
    StatsMixin,
    MenuUIMixin,
    UIMixin,
    JournalUIMixin,
    LogUIMixin,
    DeathUIMixin,
    InspectMixin,
    ControlsMixin,
    AutoexploreMixin,
    VisibilityMixin,
    CombatMixin,
    CombatAIMixin,
    HarvestMixin,
    SocialQuestsMixin,
    InventoryMixin,
    InventoryUseMixin,
    QuestTextMixin,
    QuestsMixin,
):
    DIRECTION_VECTORS = {
        "north": (0, -1),
        "south": (0, 1),
        "west": (-1, 0),
        "east": (1, 0),
    }

    WEAPON_CATALOG = {
        "dagger":   {"name": "Dagger",   "melee_bonus": 1, "ranged_bonus": 0, "cost": 3, "color": COLOR_ITEM_WEAPON, "description": "A light blade for quick close work."},
        "shortbow": {"name": "Shortbow", "melee_bonus": 0, "ranged_bonus": 1, "cost": 2, "color": COLOR_ITEM_WEAPON, "description": "A compact bow — cheap and reliable at short range."},
        "longbow":  {"name": "Longbow",  "melee_bonus": 0, "ranged_bonus": 2, "cost": 4, "color": COLOR_ITEM_WEAPON, "description": "A steady bow for open-country fights."},
        "warhammer":{"name": "Warhammer","melee_bonus": 2, "ranged_bonus": 0, "cost": 5, "color": COLOR_ITEM_WEAPON, "description": "A crushing weapon for tight, brutal fights."},
        "spear":    {"name": "Spear",    "melee_bonus": 1, "ranged_bonus": 1, "cost": 5, "color": COLOR_ITEM_WEAPON, "description": "Balanced reach for skirmishing on the move."},
        "halberd":  {"name": "Halberd",  "melee_bonus": 2, "ranged_bonus": 1, "cost": 8, "color": COLOR_ITEM_WEAPON, "description": "A heavy polearm that commands every range of the fight."},
    }
    ARMOR_CATALOG = {
        "travel_cloak":  {"name": "Travel Cloak",   "defense_bonus": 1, "cost": 2, "color": COLOR_ITEM_ARMOR, "description": "Light protection that does not slow the stride."},
        "leather_armor": {"name": "Leather Armor",  "defense_bonus": 2, "cost": 4, "color": COLOR_ITEM_ARMOR, "description": "Layered hide that takes the worst edge off."},
        "chain_mail":    {"name": "Chain Mail",      "defense_bonus": 3, "cost": 6, "color": COLOR_ITEM_ARMOR, "description": "Reliable armor for harsher country."},
        "plate_coat":    {"name": "Plate Coat",      "defense_bonus": 4, "cost": 8, "color": COLOR_ITEM_ARMOR, "description": "Heavy protection for serious delving."},
        "war_plate":     {"name": "War Plate",       "defense_bonus": 5, "cost": 10, "color": COLOR_ITEM_ARMOR, "description": "Full combat plating — hard to move in, hard to put down."},
    }
